# Generated by Django 4.0.4 on 2022-05-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('sinopsis', models.TextField()),
                ('portada', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIMDb.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIMDb.pelicula')),
            ],
        ),
    ]
