# Generated by Django 4.0.4 on 2022-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIMDb', '0002_genero_pelicula_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='codigo',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
