# Generated by Django 4.0.4 on 2022-05-24 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appIMDb', '0004_alter_rating_usuario_alter_review_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
