# Generated by Django 4.0.4 on 2022-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIMDb', '0005_review_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='calificacion',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='texto',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
