# Generated by Django 4.0.4 on 2022-05-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIMDb', '0007_pelicula_favoritos_alter_review_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(max_length=500),
        ),
    ]
