# Generated by Django 4.0.4 on 2022-06-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIMDb', '0008_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='review',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
